#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: a123
#    url: jdbc:mysql://localhost:3306/glass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8