# 开启MVC隐藏域提交方式
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8805
# dubbo的配置
dubbo:
  application:
    name: microservice-department-controller
  registry:
    protocol: zookeeper
    address: zookeeper://192.167.10.80:2181?backup=192.168.10.81:2181,192.168.10.82:2181
    subscribe: true
  protocol:
    name: dubbo
    port: 20885
  provider:
    timeout: 8000
  monitor:
    protocol: register